import type { APIRoute } from 'astro';

// Clean sample offers data - all special characters removed
const SAMPLE_OFFERS = [
  {
    id: '1',
    title: 'Complete Quick Survey - Earn $5',
    description: 'Share your opinion in this quick 5-minute survey about shopping habits and earn instant rewards.',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=240&fit=crop',
    payout: 5.00,
    currency: '$',
    countries: 'US, CA, GB, AU',
    category: 'survey',
    url: 'https://example.com/survey1',
    device: 'Any',
    terms: 'Complete the survey honestly. Must be 18+ years old.',
    estimated_time: '5 min'
  },
  {
    id: '2',
    title: 'Download Mobile Game - Get $3',
    description: 'Download and play this exciting new mobile game for 10 minutes to earn rewards.',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=240&fit=crop',
    payout: 3.00,
    currency: '$',
    countries: 'Worldwide',
    category: 'app',
    url: 'https://example.com/game1',
    device: 'Mobile',
    terms: 'Download app and play for at least 10 minutes.',
    estimated_time: '10 min'
  },
  {
    id: '3',
    title: 'Try Streaming Service - Earn $15',
    description: 'Sign up for a free trial of this popular streaming service and get paid.',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400&h=240&fit=crop',
    payout: 15.00,
    currency: '$',
    countries: 'US, GB, CA',
    category: 'trial',
    url: 'https://example.com/streaming',
    device: 'Any',
    terms: 'Valid credit card required for free trial. Cancel anytime.',
    estimated_time: '3 min'
  },
  {
    id: '4',
    title: 'Product Review Survey - $7',
    description: 'Review your recent purchases and provide detailed feedback to earn money.',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=240&fit=crop',
    payout: 7.00,
    currency: '$',
    countries: 'US, PH, GB, AU, CA',
    category: 'survey',
    url: 'https://example.com/review',
    device: 'Any',
    terms: 'Must have made a purchase in the last 30 days.',
    estimated_time: '8 min'
  },
  {
    id: '5',
    title: 'Install Shopping App - Get $4',
    description: 'Install this popular shopping app and browse for 5 minutes to get rewarded.',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=240&fit=crop',
    payout: 4.00,
    currency: '$',
    countries: 'Worldwide',
    category: 'app',
    url: 'https://example.com/shopping-app',
    device: 'Mobile',
    terms: 'Install app and browse products for 5 minutes.',
    estimated_time: '5 min'
  },
  {
    id: '6',
    title: 'Financial Services Survey - $10',
    description: 'Answer questions about your banking and financial habits in this survey.',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=240&fit=crop',
    payout: 10.00,
    currency: '$',
    countries: 'US, CA, GB',
    category: 'survey',
    url: 'https://example.com/financial',
    device: 'Any',
    terms: 'Must be 21+ and have a bank account.',
    estimated_time: '12 min'
  },
  {
    id: '7',
    title: 'Play Casual Game - Earn $2.50',
    description: 'Reach level 5 in this addictive puzzle game and earn cash rewards.',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=240&fit=crop',
    payout: 2.50,
    currency: '$',
    countries: 'Worldwide',
    category: 'game',
    url: 'https://example.com/puzzle',
    device: 'Mobile',
    terms: 'Download game and reach level 5.',
    estimated_time: '15 min'
  },
  {
    id: '8',
    title: 'VPN Service Trial - $12',
    description: 'Try this premium VPN service with a 30-day free trial and get paid.',
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&h=240&fit=crop',
    payout: 12.00,
    currency: '$',
    countries: 'US, GB, CA, AU',
    category: 'trial',
    url: 'https://example.com/vpn',
    device: 'Any',
    terms: 'Sign up for free trial. Cancel anytime.',
    estimated_time: '4 min'
  },
  {
    id: '9',
    title: 'Health and Wellness Survey - $6',
    description: 'Share your health and fitness routines in this comprehensive survey.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=240&fit=crop',
    payout: 6.00,
    currency: '$',
    countries: 'US, PH, CA, AU',
    category: 'survey',
    url: 'https://example.com/health',
    device: 'Any',
    terms: 'Complete health questionnaire honestly.',
    estimated_time: '7 min'
  },
  {
    id: '10',
    title: 'Install Fitness App - Get $3.50',
    description: 'Download this fitness tracking app and complete the initial setup process.',
    image: 'https://images.unsplash.com/photo-1461088945293-0c17689e48ac?w=400&h=240&fit=crop',
    payout: 3.50,
    currency: '$',
    countries: 'Worldwide',
    category: 'app',
    url: 'https://example.com/fitness',
    device: 'Mobile',
    terms: 'Install app and complete initial setup.',
    estimated_time: '6 min'
  },
  {
    id: '11',
    title: 'E-Learning Platform Trial - $20',
    description: 'Sign up for a premium online learning platform trial and explore courses.',
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&h=240&fit=crop',
    payout: 20.00,
    currency: '$',
    countries: 'US, GB, CA',
    category: 'trial',
    url: 'https://example.com/elearning',
    device: 'Any',
    terms: 'Start free trial of e-learning platform.',
    estimated_time: '5 min'
  },
  {
    id: '12',
    title: 'Travel Survey - Earn $8',
    description: 'Tell us about your travel preferences and habits in this detailed survey.',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=240&fit=crop',
    payout: 8.00,
    currency: '$',
    countries: 'US, PH, GB, AU, CA',
    category: 'survey',
    url: 'https://example.com/travel',
    device: 'Any',
    terms: 'Share your travel experiences and preferences.',
    estimated_time: '10 min'
  },
  {
    id: '13',
    title: 'Casino Game App - Get $5',
    description: 'Play this social casino game and reach level 3 to earn your reward.',
    image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=400&h=240&fit=crop',
    payout: 5.00,
    currency: '$',
    countries: 'US, CA, GB',
    category: 'game',
    url: 'https://example.com/casino',
    device: 'Mobile',
    terms: 'Play social casino game. Must be 21+.',
    estimated_time: '20 min'
  },
  {
    id: '14',
    title: 'Cloud Storage Trial - $10',
    description: 'Try premium cloud storage with 100GB free trial and get paid for signing up.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&h=240&fit=crop',
    payout: 10.00,
    currency: '$',
    countries: 'Worldwide',
    category: 'trial',
    url: 'https://example.com/cloud',
    device: 'Any',
    terms: 'Sign up for cloud storage free trial.',
    estimated_time: '3 min'
  },
  {
    id: '15',
    title: 'Food Delivery Survey - $4.50',
    description: 'Share your food delivery app experiences and preferences with us.',
    image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=400&h=240&fit=crop',
    payout: 4.50,
    currency: '$',
    countries: 'US, PH, GB, AU, CA',
    category: 'survey',
    url: 'https://example.com/food',
    device: 'Any',
    terms: 'Complete food delivery survey.',
    estimated_time: '6 min'
  },
  {
    id: '16',
    title: 'Recipe App Download - Earn $3',
    description: 'Download this cooking app and save 3 recipes to earn your reward.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=240&fit=crop',
    payout: 3.00,
    currency: '$',
    countries: 'Worldwide',
    category: 'app',
    url: 'https://example.com/recipe',
    device: 'Mobile',
    terms: 'Install recipe app and save 3 recipes.',
    estimated_time: '5 min'
  },
  {
    id: '17',
    title: 'Music Streaming Trial - $8',
    description: 'Try premium music service with a 3-month free trial and get rewarded.',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=240&fit=crop',
    payout: 8.00,
    currency: '$',
    countries: 'US, GB, CA, AU',
    category: 'trial',
    url: 'https://example.com/music',
    device: 'Any',
    terms: 'Start free trial. Cancel anytime.',
    estimated_time: '4 min'
  },
  {
    id: '18',
    title: 'Technology Survey - Get $9',
    description: 'Answer questions about your tech usage and preferences in this survey.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=240&fit=crop',
    payout: 9.00,
    currency: '$',
    countries: 'US, PH, GB, CA',
    category: 'survey',
    url: 'https://example.com/tech',
    device: 'Any',
    terms: 'Complete technology survey.',
    estimated_time: '11 min'
  },
  {
    id: '19',
    title: 'Word Game Challenge - $2',
    description: 'Complete 10 levels in this word puzzle game to earn your cash reward.',
    image: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=240&fit=crop',
    payout: 2.00,
    currency: '$',
    countries: 'Worldwide',
    category: 'game',
    url: 'https://example.com/wordgame',
    device: 'Mobile',
    terms: 'Play word game and complete 10 levels.',
    estimated_time: '12 min'
  },
  {
    id: '20',
    title: 'Password Manager Trial - $15',
    description: 'Try this premium password manager with advanced security features.',
    image: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=240&fit=crop',
    payout: 15.00,
    currency: '$',
    countries: 'US, GB, CA, AU',
    category: 'trial',
    url: 'https://example.com/password',
    device: 'Any',
    terms: 'Sign up for password manager trial.',
    estimated_time: '5 min'
  }
];

export const GET: APIRoute = async () => {
  return new Response(JSON.stringify(SAMPLE_OFFERS), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'Access-Control-Allow-Origin': '*'
    },
  });
};
